// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/EncounterData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

GPB_ENUM_FWD_DECLARE(PokemonId);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - EncounterDataRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface EncounterDataRoot : GPBRootObject
@end

#pragma mark - EncounterData

typedef GPB_ENUM(EncounterData_FieldNumber) {
  EncounterData_FieldNumber_PokemonId = 1,
  EncounterData_FieldNumber_FoundTime = 2,
  EncounterData_FieldNumber_ExpirationTime = 3,
  EncounterData_FieldNumber_Latitude = 4,
  EncounterData_FieldNumber_Longitude = 5,
};

@interface EncounterData : GPBMessage

@property(nonatomic, readwrite) enum PokemonId pokemonId;

@property(nonatomic, readwrite) uint64_t foundTime;

@property(nonatomic, readwrite) uint64_t expirationTime;

@property(nonatomic, readwrite) double latitude;

@property(nonatomic, readwrite) double longitude;

@end

/// Fetches the raw value of a @c EncounterData's @c pokemonId property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t EncounterData_PokemonId_RawValue(EncounterData *message);
/// Sets the raw value of an @c EncounterData's @c pokemonId property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetEncounterData_PokemonId_RawValue(EncounterData *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
