// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/EncounterData.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/GoMap/EncounterData.pbobjc.h"
 #import "POGOProtos/Enums/PokemonId.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - EncounterDataRoot

@implementation EncounterDataRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[PokemonIdRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - EncounterDataRoot_FileDescriptor

static GPBFileDescriptor *EncounterDataRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.GoMap"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - EncounterData

@implementation EncounterData

@dynamic pokemonId;
@dynamic foundTime;
@dynamic expirationTime;
@dynamic latitude;
@dynamic longitude;

typedef struct EncounterData__storage_ {
  uint32_t _has_storage_[1];
  PokemonId pokemonId;
  uint64_t foundTime;
  uint64_t expirationTime;
  double latitude;
  double longitude;
} EncounterData__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "pokemonId",
        .dataTypeSpecific.enumDescFunc = PokemonId_EnumDescriptor,
        .number = EncounterData_FieldNumber_PokemonId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(EncounterData__storage_, pokemonId),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "foundTime",
        .dataTypeSpecific.className = NULL,
        .number = EncounterData_FieldNumber_FoundTime,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(EncounterData__storage_, foundTime),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "expirationTime",
        .dataTypeSpecific.className = NULL,
        .number = EncounterData_FieldNumber_ExpirationTime,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(EncounterData__storage_, expirationTime),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "latitude",
        .dataTypeSpecific.className = NULL,
        .number = EncounterData_FieldNumber_Latitude,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(EncounterData__storage_, latitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
      {
        .name = "longitude",
        .dataTypeSpecific.className = NULL,
        .number = EncounterData_FieldNumber_Longitude,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(EncounterData__storage_, longitude),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeDouble,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[EncounterData class]
                                     rootClass:[EncounterDataRoot class]
                                          file:EncounterDataRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(EncounterData__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t EncounterData_PokemonId_RawValue(EncounterData *message) {
  GPBDescriptor *descriptor = [EncounterData descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:EncounterData_FieldNumber_PokemonId];
  return GPBGetMessageInt32Field(message, field);
}

void SetEncounterData_PokemonId_RawValue(EncounterData *message, int32_t value) {
  GPBDescriptor *descriptor = [EncounterData descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:EncounterData_FieldNumber_PokemonId];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
