// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/GetPlayerInfoResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class GymHistory;
@class PlayerActivityLog;
@class PokemonData;
GPB_ENUM_FWD_DECLARE(TeamColor);

NS_ASSUME_NONNULL_BEGIN

#pragma mark - GetPlayerInfoResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface GetPlayerInfoResponseRoot : GPBRootObject
@end

#pragma mark - GetPlayerInfoResponse

typedef GPB_ENUM(GetPlayerInfoResponse_FieldNumber) {
  GetPlayerInfoResponse_FieldNumber_TeamColor = 1,
  GetPlayerInfoResponse_FieldNumber_PokemonArray = 2,
  GetPlayerInfoResponse_FieldNumber_RecentActivityArray = 3,
  GetPlayerInfoResponse_FieldNumber_GymHistoryArray = 4,
  GetPlayerInfoResponse_FieldNumber_GymIdsArray = 5,
};

@interface GetPlayerInfoResponse : GPBMessage

@property(nonatomic, readwrite) enum TeamColor teamColor;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PokemonData*> *pokemonArray;
/// The number of items in @c pokemonArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger pokemonArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<PlayerActivityLog*> *recentActivityArray;
/// The number of items in @c recentActivityArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger recentActivityArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GymHistory*> *gymHistoryArray;
/// The number of items in @c gymHistoryArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger gymHistoryArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *gymIdsArray;
/// The number of items in @c gymIdsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger gymIdsArray_Count;

@end

/// Fetches the raw value of a @c GetPlayerInfoResponse's @c teamColor property, even
/// if the value was not defined by the enum at the time the code was generated.
int32_t GetPlayerInfoResponse_TeamColor_RawValue(GetPlayerInfoResponse *message);
/// Sets the raw value of an @c GetPlayerInfoResponse's @c teamColor property, allowing
/// it to be set to a value that was not defined by the enum at the time the code
/// was generated.
void SetGetPlayerInfoResponse_TeamColor_RawValue(GetPlayerInfoResponse *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
