// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/GetPlayerInfoResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/GoMap/GetPlayerInfoResponse.pbobjc.h"
 #import "POGOProtos/Enums/TeamColor.pbobjc.h"
 #import "POGOProtos/Data/PokemonData.pbobjc.h"
 #import "POGOProtos/GoMap/PlayerActivityLog.pbobjc.h"
 #import "POGOProtos/GoMap/GymHistory.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GetPlayerInfoResponseRoot

@implementation GetPlayerInfoResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[TeamColorRoot extensionRegistry]];
    [registry addExtensions:[PokemonDataRoot extensionRegistry]];
    [registry addExtensions:[PlayerActivityLogRoot extensionRegistry]];
    [registry addExtensions:[GymHistoryRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GetPlayerInfoResponseRoot_FileDescriptor

static GPBFileDescriptor *GetPlayerInfoResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.GoMap"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GetPlayerInfoResponse

@implementation GetPlayerInfoResponse

@dynamic teamColor;
@dynamic pokemonArray, pokemonArray_Count;
@dynamic recentActivityArray, recentActivityArray_Count;
@dynamic gymHistoryArray, gymHistoryArray_Count;
@dynamic gymIdsArray, gymIdsArray_Count;

typedef struct GetPlayerInfoResponse__storage_ {
  uint32_t _has_storage_[1];
  TeamColor teamColor;
  NSMutableArray *pokemonArray;
  NSMutableArray *recentActivityArray;
  NSMutableArray *gymHistoryArray;
  NSMutableArray *gymIdsArray;
} GetPlayerInfoResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "teamColor",
        .dataTypeSpecific.enumDescFunc = TeamColor_EnumDescriptor,
        .number = GetPlayerInfoResponse_FieldNumber_TeamColor,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GetPlayerInfoResponse__storage_, teamColor),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "pokemonArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PokemonData),
        .number = GetPlayerInfoResponse_FieldNumber_PokemonArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetPlayerInfoResponse__storage_, pokemonArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "recentActivityArray",
        .dataTypeSpecific.className = GPBStringifySymbol(PlayerActivityLog),
        .number = GetPlayerInfoResponse_FieldNumber_RecentActivityArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetPlayerInfoResponse__storage_, recentActivityArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "gymHistoryArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GymHistory),
        .number = GetPlayerInfoResponse_FieldNumber_GymHistoryArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetPlayerInfoResponse__storage_, gymHistoryArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "gymIdsArray",
        .dataTypeSpecific.className = NULL,
        .number = GetPlayerInfoResponse_FieldNumber_GymIdsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GetPlayerInfoResponse__storage_, gymIdsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GetPlayerInfoResponse class]
                                     rootClass:[GetPlayerInfoResponseRoot class]
                                          file:GetPlayerInfoResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GetPlayerInfoResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GetPlayerInfoResponse_TeamColor_RawValue(GetPlayerInfoResponse *message) {
  GPBDescriptor *descriptor = [GetPlayerInfoResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetPlayerInfoResponse_FieldNumber_TeamColor];
  return GPBGetMessageInt32Field(message, field);
}

void SetGetPlayerInfoResponse_TeamColor_RawValue(GetPlayerInfoResponse *message, int32_t value) {
  GPBDescriptor *descriptor = [GetPlayerInfoResponse descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GetPlayerInfoResponse_FieldNumber_TeamColor];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
