// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/GlobalActivityLog.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/GoMap/GlobalActivityLog.pbobjc.h"
 #import "POGOProtos/GoMap/GymActivityType.pbobjc.h"
 #import "POGOProtos/Enums/TeamColor.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GlobalActivityLogRoot

@implementation GlobalActivityLogRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[GymActivityTypeRoot extensionRegistry]];
    [registry addExtensions:[TeamColorRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GlobalActivityLogRoot_FileDescriptor

static GPBFileDescriptor *GlobalActivityLogRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.GoMap"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GlobalActivityLog

@implementation GlobalActivityLog

@dynamic timestamp;
@dynamic gymId;
@dynamic type;
@dynamic team;
@dynamic playerName;

typedef struct GlobalActivityLog__storage_ {
  uint32_t _has_storage_[1];
  GymActivityType type;
  TeamColor team;
  NSString *gymId;
  NSString *playerName;
  uint64_t timestamp;
} GlobalActivityLog__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "timestamp",
        .dataTypeSpecific.className = NULL,
        .number = GlobalActivityLog_FieldNumber_Timestamp,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(GlobalActivityLog__storage_, timestamp),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeUInt64,
      },
      {
        .name = "gymId",
        .dataTypeSpecific.className = NULL,
        .number = GlobalActivityLog_FieldNumber_GymId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(GlobalActivityLog__storage_, gymId),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "type",
        .dataTypeSpecific.enumDescFunc = GymActivityType_EnumDescriptor,
        .number = GlobalActivityLog_FieldNumber_Type,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(GlobalActivityLog__storage_, type),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "team",
        .dataTypeSpecific.enumDescFunc = TeamColor_EnumDescriptor,
        .number = GlobalActivityLog_FieldNumber_Team,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(GlobalActivityLog__storage_, team),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "playerName",
        .dataTypeSpecific.className = NULL,
        .number = GlobalActivityLog_FieldNumber_PlayerName,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(GlobalActivityLog__storage_, playerName),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GlobalActivityLog class]
                                     rootClass:[GlobalActivityLogRoot class]
                                          file:GlobalActivityLogRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GlobalActivityLog__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t GlobalActivityLog_Type_RawValue(GlobalActivityLog *message) {
  GPBDescriptor *descriptor = [GlobalActivityLog descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GlobalActivityLog_FieldNumber_Type];
  return GPBGetMessageInt32Field(message, field);
}

void SetGlobalActivityLog_Type_RawValue(GlobalActivityLog *message, int32_t value) {
  GPBDescriptor *descriptor = [GlobalActivityLog descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GlobalActivityLog_FieldNumber_Type];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

int32_t GlobalActivityLog_Team_RawValue(GlobalActivityLog *message) {
  GPBDescriptor *descriptor = [GlobalActivityLog descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GlobalActivityLog_FieldNumber_Team];
  return GPBGetMessageInt32Field(message, field);
}

void SetGlobalActivityLog_Team_RawValue(GlobalActivityLog *message, int32_t value) {
  GPBDescriptor *descriptor = [GlobalActivityLog descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:GlobalActivityLog_FieldNumber_Team];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
