// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/GlobalActivityResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/GoMap/GlobalActivityResponse.pbobjc.h"
 #import "POGOProtos/GoMap/GlobalActivityLog.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - GlobalActivityResponseRoot

@implementation GlobalActivityResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[GlobalActivityLogRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - GlobalActivityResponseRoot_FileDescriptor

static GPBFileDescriptor *GlobalActivityResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.GoMap"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - GlobalActivityResponse

@implementation GlobalActivityResponse

@dynamic activityArray, activityArray_Count;

typedef struct GlobalActivityResponse__storage_ {
  uint32_t _has_storage_[1];
  NSMutableArray *activityArray;
} GlobalActivityResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "activityArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GlobalActivityLog),
        .number = GlobalActivityResponse_FieldNumber_ActivityArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(GlobalActivityResponse__storage_, activityArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[GlobalActivityResponse class]
                                     rootClass:[GlobalActivityResponseRoot class]
                                          file:GlobalActivityResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(GlobalActivityResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
