// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/NotificationSetting.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/GoMap/NotificationSetting.pbobjc.h"
 #import "POGOProtos/Enums/PokemonId.pbobjc.h"
 #import "POGOProtos/GoMap/NotificationType.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - NotificationSettingRoot

@implementation NotificationSettingRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[PokemonIdRoot extensionRegistry]];
    [registry addExtensions:[NotificationTypeRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - NotificationSettingRoot_FileDescriptor

static GPBFileDescriptor *NotificationSettingRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.GoMap"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - NotificationSetting

@implementation NotificationSetting

@dynamic pokemonId;
@dynamic notificationType;

typedef struct NotificationSetting__storage_ {
  uint32_t _has_storage_[1];
  PokemonId pokemonId;
  NotificationType notificationType;
} NotificationSetting__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "pokemonId",
        .dataTypeSpecific.enumDescFunc = PokemonId_EnumDescriptor,
        .number = NotificationSetting_FieldNumber_PokemonId,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(NotificationSetting__storage_, pokemonId),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
      {
        .name = "notificationType",
        .dataTypeSpecific.enumDescFunc = NotificationType_EnumDescriptor,
        .number = NotificationSetting_FieldNumber_NotificationType,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(NotificationSetting__storage_, notificationType),
        .flags = GPBFieldOptional | GPBFieldHasEnumDescriptor,
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[NotificationSetting class]
                                     rootClass:[NotificationSettingRoot class]
                                          file:NotificationSettingRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(NotificationSetting__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t NotificationSetting_PokemonId_RawValue(NotificationSetting *message) {
  GPBDescriptor *descriptor = [NotificationSetting descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:NotificationSetting_FieldNumber_PokemonId];
  return GPBGetMessageInt32Field(message, field);
}

void SetNotificationSetting_PokemonId_RawValue(NotificationSetting *message, int32_t value) {
  GPBDescriptor *descriptor = [NotificationSetting descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:NotificationSetting_FieldNumber_PokemonId];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}

int32_t NotificationSetting_NotificationType_RawValue(NotificationSetting *message) {
  GPBDescriptor *descriptor = [NotificationSetting descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:NotificationSetting_FieldNumber_NotificationType];
  return GPBGetMessageInt32Field(message, field);
}

void SetNotificationSetting_NotificationType_RawValue(NotificationSetting *message, int32_t value) {
  GPBDescriptor *descriptor = [NotificationSetting descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:NotificationSetting_FieldNumber_NotificationType];
  GPBSetInt32IvarWithFieldInternal(message, field, value, descriptor.file.syntax);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
