// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/UpdateNotificationsRequest.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/GoMap/UpdateNotificationsRequest.pbobjc.h"
 #import "POGOProtos/GoMap/NotificationSetting.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UpdateNotificationsRequestRoot

@implementation UpdateNotificationsRequestRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[NotificationSettingRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - UpdateNotificationsRequestRoot_FileDescriptor

static GPBFileDescriptor *UpdateNotificationsRequestRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.GoMap"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UpdateNotificationsRequest

@implementation UpdateNotificationsRequest

@dynamic deviceIdentifier;
@dynamic settingsArray, settingsArray_Count;

typedef struct UpdateNotificationsRequest__storage_ {
  uint32_t _has_storage_[1];
  NSString *deviceIdentifier;
  NSMutableArray *settingsArray;
} UpdateNotificationsRequest__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "deviceIdentifier",
        .dataTypeSpecific.className = NULL,
        .number = UpdateNotificationsRequest_FieldNumber_DeviceIdentifier,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UpdateNotificationsRequest__storage_, deviceIdentifier),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeString,
      },
      {
        .name = "settingsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(NotificationSetting),
        .number = UpdateNotificationsRequest_FieldNumber_SettingsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(UpdateNotificationsRequest__storage_, settingsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UpdateNotificationsRequest class]
                                     rootClass:[UpdateNotificationsRequestRoot class]
                                          file:UpdateNotificationsRequestRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UpdateNotificationsRequest__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
