// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/UpdateDataResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

 #import "POGOProtos/GoMap/UpdateDataResponse.pbobjc.h"
 #import "POGOProtos/GoMap/GlobalActivityLog.pbobjc.h"
 #import "POGOProtos/Networking/Responses/GetGymDetailsResponse.pbobjc.h"
 #import "POGOProtos/GoMap/EncounterData.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - UpdateDataResponseRoot

@implementation UpdateDataResponseRoot

+ (GPBExtensionRegistry*)extensionRegistry {
  // This is called by +initialize so there is no need to worry
  // about thread safety and initialization of registry.
  static GPBExtensionRegistry* registry = nil;
  if (!registry) {
    GPBDebugCheckRuntimeVersion();
    registry = [[GPBExtensionRegistry alloc] init];
    [registry addExtensions:[GlobalActivityLogRoot extensionRegistry]];
    [registry addExtensions:[GetGymDetailsResponseRoot extensionRegistry]];
    [registry addExtensions:[EncounterDataRoot extensionRegistry]];
  }
  return registry;
}

@end

#pragma mark - UpdateDataResponseRoot_FileDescriptor

static GPBFileDescriptor *UpdateDataResponseRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPBDebugCheckRuntimeVersion();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@"POGOProtos.GoMap"
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - UpdateDataResponse

@implementation UpdateDataResponse

@dynamic activityArray, activityArray_Count;
@dynamic gymsDetailsArray, gymsDetailsArray_Count;
@dynamic encounterArray, encounterArray_Count;
@dynamic status;

typedef struct UpdateDataResponse__storage_ {
  uint32_t _has_storage_[1];
  int32_t status;
  NSMutableArray *activityArray;
  NSMutableArray *gymsDetailsArray;
  NSMutableArray *encounterArray;
} UpdateDataResponse__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "activityArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GlobalActivityLog),
        .number = UpdateDataResponse_FieldNumber_ActivityArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(UpdateDataResponse__storage_, activityArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "gymsDetailsArray",
        .dataTypeSpecific.className = GPBStringifySymbol(GetGymDetailsResponse),
        .number = UpdateDataResponse_FieldNumber_GymsDetailsArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(UpdateDataResponse__storage_, gymsDetailsArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "encounterArray",
        .dataTypeSpecific.className = GPBStringifySymbol(EncounterData),
        .number = UpdateDataResponse_FieldNumber_EncounterArray,
        .hasIndex = GPBNoHasBit,
        .offset = (uint32_t)offsetof(UpdateDataResponse__storage_, encounterArray),
        .flags = GPBFieldRepeated,
        .dataType = GPBDataTypeMessage,
      },
      {
        .name = "status",
        .dataTypeSpecific.className = NULL,
        .number = UpdateDataResponse_FieldNumber_Status,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(UpdateDataResponse__storage_, status),
        .flags = GPBFieldOptional,
        .dataType = GPBDataTypeInt32,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[UpdateDataResponse class]
                                     rootClass:[UpdateDataResponseRoot class]
                                          file:UpdateDataResponseRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(UpdateDataResponse__storage_)
                                         flags:0];
    NSAssert(descriptor == nil, @"Startup recursed!");
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
