// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/GoMap/UpdateDataResponse.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_GEN_VERSION != 30001
#error This file was generated by a different version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class EncounterData;
@class GetGymDetailsResponse;
@class GlobalActivityLog;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - UpdateDataResponseRoot

/// Exposes the extension registry for this file.
///
/// The base class provides:
/// @code
///   + (GPBExtensionRegistry *)extensionRegistry;
/// @endcode
/// which is a @c GPBExtensionRegistry that includes all the extensions defined by
/// this file and all files that it depends on.
@interface UpdateDataResponseRoot : GPBRootObject
@end

#pragma mark - UpdateDataResponse

typedef GPB_ENUM(UpdateDataResponse_FieldNumber) {
  UpdateDataResponse_FieldNumber_ActivityArray = 1,
  UpdateDataResponse_FieldNumber_GymsDetailsArray = 2,
  UpdateDataResponse_FieldNumber_EncounterArray = 3,
  UpdateDataResponse_FieldNumber_Status = 4,
};

@interface UpdateDataResponse : GPBMessage

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GlobalActivityLog*> *activityArray;
/// The number of items in @c activityArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger activityArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<GetGymDetailsResponse*> *gymsDetailsArray;
/// The number of items in @c gymsDetailsArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger gymsDetailsArray_Count;

@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<EncounterData*> *encounterArray;
/// The number of items in @c encounterArray without causing the array to be created.
@property(nonatomic, readonly) NSUInteger encounterArray_Count;

@property(nonatomic, readwrite) int32_t status;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
